> 开发过程中通常需要 属于我们自己的错误类来反应任务中可能出现的特殊情况。
> 对于网络错误操作： 我们需要 HttpError
> 对于数据库操作错误: 我们需要 DbError
> 对于搜索操作错误，我们需要 NotFoundError

> 我们自定义的错误 应该具有基本的错误属性，例如 message， name 以及更详细的 stack。

> JS 允许我们 throw 时 带任何参数

### 扩展错误

让我们用一个能够读取用户数据的函数 readUser(json) 来作为例子。
这里是一个可用的 json 的例子：

```
let json = `{ "name": "John", "age": 30 }`;
```

但即使是格式正确的 json，也并不表示它就是可用的，对吧？它有可能会遗漏一些必要的数据。例如，缺失了对用户所必需的 name 和 age 属性。

函数 readUser(json) 不仅会读取 JSON，也会检查（验证）数据。如果没有所需要的字段，或者格式不正确，那也是错误。而这不是 SyntaxError，因为数据在语法上是正确的，但是有其他的错误。我们称之为 ValidationError 并且为之创建一个类。这种类型的错误也应该承载缺少的字段的信息。

> 我们的 ValidationError 类应该继承自内置的 Error 类。
> Error 类是内置的，但是我们需要看一下大致的代码，来理解我们需要扩展什么。

```
// 由JavaScript本身定义的内置错误类“伪代码”
class Error {
  constructor(message) {
    this.message = message;
    this.name = "Error"; //（不同内置错误类别的名称）
    this.stack = <nested calls>; // 非标准，但大多数环境支持它
  }
}
```

现在让我们开始用 ValidationError 来进行继承：

```
class ValidationError extends Error {
  constructor(message) {
    super(message); // (1)
    this.name = "ValidationError"; // (2)
  }}
function test() {
  throw new ValidationError("Whoops!");
}
try {
  test();
}
catch(err) {
  alert(err.message); // Whoops!
  alert(err.name); // 验证错误
  alert(err.stack); // 每个行编号的嵌套调用列表}
```
